Fix webpack config globalObject for NextJS / SSR compatibility
seawind543/react-token-input pull request #53
Opened 2021-11-25 21:38 UTC by wfortin

This solves #52.

See https://stackoverflow.com/questions/64639839/typescript-webpack-library-generates-referenceerror-self-is-not-defined.

Tested locally in a Next JS SSR projects and it solves the issue. I would really appreciate if you could publish a new version with this fix.

2021-12-10 15:49 UTC, seawind543 commented
Hi @wfortin, 
Thank you for the information and also for providing the solution. I had planned to make a new release soon and would like to include the fix of #52 👍  
Therefore, I'm wondering does there any help can I provide for this pull request?

2021-12-10 21:20 UTC, wfortin commented
https://github.com/seawind543/react-token-input/pull/53/files#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR27
This is the only change that is needed if you can bundle it in the release that would be greatly appreciated.

2021-12-11 05:41 UTC, seawind543 requested changes
Hi @wfortin,

Apologize for the late response and inconvenience. I find out what happened now, it looks like I did not public my previous code-review comment 😭
This is my first time to make code-review via GitHub. Please let me know if I did anything wrong 🙏

2021-12-17 17:05 UTC, wfortin commented on docs/index.html
> +<script defer src="bundle.js?12c7528d60e958cc1795"></script></head>
Resolved now.

2021-12-17 17:08 UTC, wfortin commented on docs/index.html
> +<script defer src="bundle.js?12c7528d60e958cc1795"></script></head>
Fixed the merge conflicts.

2021-12-18 03:41 UTC, seawind543 approved these changes
Hi @wfortin, Thanks for the fix. I will release a new version soon 👍

2021-12-18 03:47 UTC, merged